### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by jenseneverest** [zgemma-star/meta-zgemma#12]
Any chance these links could be restored or could you please provide the missing files

`git clone https://github.com/zgemma-star/aosp/h9-device device/hisilicon/h9 
git clone https://github.com/zgemma-star/aosp/kernel device/hisilicon/kernel 
git clone https://github.com/zgemma-star/aosp/h9-vendor vendor/hisilicon/h9 `

Would like to try compile AOSP if possible

TIA

**Comment by zgemma-star** [comment]
The AOSP layer contains files which are under license and so that's why it isn't yet public available.

**Comment by Rzaandroid** [comment]
Hi Jensen I need to build android for the same box did you get it working ?
Msg me at rza.android@gmail.com
