### ISSUE TITLE
vtuner issue (satipclient)

### ISSUE THREAD

**Issue by perexg** [zgemma-star/meta-zgemma#13]
I would like to report a problem with the vtuner on zgemma-h7c . The ioctls() between enigma2 and satipclient took really long time so the frontend stalls. It appears like a queuing issue in the virtual tuner code in h7 kernel modules. Please, could you give a look? You can test this with the minisatip server (already as package in openpli for example).

**Comment by zgemma-star** [comment]
Vtuner works fine on the H7 and there are no issues report at driver side.
External plugins I think you can best ask the maintainer to fix it.
Probably cause is the difference between Mipsel and ARM architecture.

**Comment by perexg** [comment]
Could you give me the vtuner code you're using in your driver? I'm using the latest openpli and the replies from the satipclient through the vtuner fd are not forwarded to enigma2 (ioctl timeout). So perhaps the structures or something changed and I need to find the correct binary format for ioctl.

**Comment by zgemma-star** [comment]
please try the fix from early 2017 which worked fine by tests:

https://github.com/oe-alliance/satip-client/blob/mis/vtuner.h#L138
Change to:
#if _IOC_NONE == 0

and in top of file the include:
#include <linux/ioctl.h>

**Comment by perexg** [comment]
Thanks, I fought with the wrong autoconf files, proposed fix which works for me: https://github.com/oe-alliance/satip-client/pull/11 . Closing this and thanks for your help.
