### ISSUE TITLE
Blind Scan H9S

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/meta-zgemma#34]
Hello **Zgemma Community**,
I recently purchased **H9S box** with fresh clean **_openATV_**  image installed.
**Blind Scan** option is not working which allows you to scan a specific satellite within a frequency range scale.
This option works on all receivers so please solve this problem which will make the **H9S** the best until now.

**Comment by zgemma-star** [comment]
Please test Openpli image as on this all seems to work fine.
So this means the problem is image related and not a driver issue.

**Comment by atvcaptain** [comment]
atv 6.2 h9s bs works, without changes found more as 100 tp i change scan max range to 10900 find only some scan time change from 2:59 to 0:32 to scan tp, have you more infos what not working ?

**Comment by Kerberos1864** [comment]
Problem solved thank you for your support !
