### ISSUE TITLE
MicroSD Compatibility

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/meta-zgemma#37]
Dear Zgemma Community,
Recording on **_1080p_** or **_4K_** channels requires a good SDcard not a cheap class 10 card.
I found a good microSD card by **Kingston** which has _100MB/s Read_ and _70MB/s Write_ speeds.
**_Canvas React_**
https://www.kingston.com/en/flash/microsd_cards/sdcr 
Can you confirm if its compatible with the **H9S** ?
Regards,

**Comment by HD-Digital** [comment]
Class 10 cards are test which were suitable for 4K record. This isn't a confirmation that a Kingston class10-3 will been compatible as our test were done with Verbatim sdcards. Normally this card should work.

**Comment by zgemma-star** [comment]
Class 10 cards are test which were suitable for 4K record. This isn't a confirmation that a Kingston class10-3 will been compatible as our test were done with Verbatim sdcards. Normally this card should work.

**Comment by Kerberos1864** [comment]
Hello normally class 10 cards have 10MB/s which is not good for 4K records.
I will buy  **Canvas React** and try
![Untitled](https://user-images.githubusercontent.com/45090310/54472075-33881400-47cb-11e9-8194-bb2435710c99.png)

**Comment by Kerberos1864** [comment]
It worked thank you !
