### ISSUE TITLE
Zgemma H7s CPU temperature

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#40]
hi, please if possible add the ability to output the CPU temperature
`root@h7:~# cat /sys/devices/virtual/thermal/thermal_zone0/temp
cat: read error: Invalid argument
root@h7:~#`

on ET 11000 this works with Broadcom BCM7251S
`root@et1x000:~# cat /sys/devices/virtual/thermal/thermal_zone0/temp
55017
root@et1x000:~#`

**Comment by zgemma-star** [comment]
The temperate is core value and it seems lot of people do not understand what's the difference between core temperature and the temperature inside the box.
The core temperature should been stabile and of a minimal temperature according Broadcom.
When you want to place a fan it should only create a flow to circulation for the "hot" air.

The picture shown as here https://github.com/oe-alliance/oe-alliance-core/issues/487#issuecomment-480649742 will reduce performance and life-time of the box as it tries to cool down the CPU core. Were not a PC so don't try to reduce CPU temp when it's not necessary.

**Comment by Marchella1983** [comment]
Yes, but you can add the output CPU temperature, I know that the chip Broadcom BCM7251S is able to...

and even without a fan on my Zgemma H7s you can boil the kettle and with a fan temperature of 45 degrees...

so I ask you to add this option, please...

or for me to take back to the seller ten boxes because of the lack of this option?

**Comment by zgemma-star** [comment]
The BCM7251s should as advise by the manufacture between minimal 70 and maximum of 115 degree.
Probably the CPU core is 80 degree with a fan and without 92degree. The temperature measure gives due outside manupilaton by a fan 45 degree.

The CPU is a part of the SOC chipset and the SOC chipset is by my measures around 30/50 degree (depend were you measure) when the airflow isn't manupilate.

**Comment by Marchella1983** [comment]
From the radiator of the processor, I measure
![20190410_150513](https://user-images.githubusercontent.com/28537448/55871337-def66f80-5ba3-11e9-81cf-aef2de38b1d5.jpg)


is it really so difficult for you to just add a temperature output?
`cat /sys/devices/virtual/thermal/thermal_zone0/temp`

**Comment by zgemma-star** [comment]
Image maker add this info to the info menu which gives almost all users a wrong inception what is meant by this info. It not about the tempeture of the box or the SOC chipset but a small part inside the SOC were the CPU is nearby. A fan clearly manupilate the sensor and gives wrong values and in any case the sensor should been disable when it use a fan.

We request by image makers to make a better solution when they don't want to remove this information from the info menu. Like inform with colors if the temperature normal, low or high. Like between 0 ~50 red 51 ~68 orange 69 ~105 green 106 ~115 orange and 115 and higher red.
As well an easy solution is to add info like "between 68 ~105 is normal" however all CPU's have other levels and operation values.
The cat /sys/devices/virtual/thermal/thermal_zone0/temp info shouldn't belong in info osd menu but it seems image makers want to inform this info to normal users which don't understand that it has nothing to do with the temperature of the box itself.

**Comment by Marchella1983** [comment]
once again, please just add something that can output a Broadcom chip BCM7251S

**Comment by jenseneverest** [comment]
i think your missing the point Marchella1983.  Zgemma removed the option to see it due to the end user not understanding the temp ranges are normal.

Why not just add a temp probe to your fan setup if your that bothered?

**Comment by Marchella1983** [comment]
@zgemma-star so will the cpu temperature output be added?

Please add it. I ask you very much ...
