### ISSUE TITLE
Zgemma H7s and H264

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#41]
Hello, can you fix it somehow? 
video with 4K H264 codec except sound there is no picture
https://mega.nz/#!xRk0hYZS!82eXs99dbTXrLl9h8hiUc5U83_ZfG36XEiuOqzafKgo

still, the there is but there is no understanding sound
https://mega.nz/#!kJEyVCrY!x9CE3j4S8VwaxKuizSENhoVXWNFl1WZhZAOS5P4wWrQ

**Comment by zgemma-star** [comment]
Broadcom chipset which is used by H7 model don't support 4K H.264
Only the with Hisilicon chipset models H9 has this codec support

**Comment by Marchella1983** [comment]
but this video not so, video 60mbit?
https://mega.nz/#!kJEyVCrY!x9CE3j4S8VwaxKuizSENhoVXWNFl1WZhZAOS5P4wWrQ

**Comment by Marchella1983** [comment]
> Only the with Hisilicon chipset models H9 has this codec support

I already ordered this model, thank you!!!
