### ISSUE TITLE
Zgemma H7S Blindscan bugs and future

### ISSUE THREAD

**Issue by zinonino** [zgemma-star/meta-zgemma#42]
Hi,
i test blindscan on H7s and work, but missing a lot options.

Don't have option to choose start and stop range for symbol rate, also don't have option to choose what transponder to scan and what to don't scan, also bug is every finded mux is with AUTO fec, must find fec, not all mux with auto.

You can see for what i talking option are missing here: https://www.youtube.com/watch?v=uwT3MKzzFyE

Bug i find, when one of tunner is not configured and run blindscan plugin get blue screen and crash, like my example i not used second sat tunner and tunner was active, but not configured by default and blindscan plugin crash, must not crash even with not configured tunner.

Thanks

**Comment by zgemma-star** [comment]
The bug of blue screen is not driver related but Enigma2, can you please inform this with the crash log in the forum of the image your using. Then hopefully they can fix it for you.
The options of transponder selection is all done in Enigma2 and it's not driver related. You should ask the maintainer of the plugin if he can add this option. 
Our tuners support AUTO-FEC, actually the FEC value is ignored by the tuner and it's sets itself on AUTO-FEC. So there is non improvement to shown the value. Only cosmetic point of view it can been of interest.

Can you tell me if you set the Symbol rate to 27499 - 27501 the scan will go quicker or that it's only costmetic that it will shown in your list only the transponders with SR of 27499 - 27501.
The tuner uses hardware blindscan and not software blindscan, so I do not think it's improves anything when this value is changed. If scanning time reduce then we will been happy to see if we can support it.

I miss in you video realtime show the found transponders. I think for feedhunters this is most essential part of the function of blindscan.

**Comment by zinonino** [comment]
[enigma2_crash_1555281491.log](https://github.com/zgemma-star/meta-zgemma/files/3081446/enigma2_crash_1555281491.log)
I will say it here, because developer on images read also here, atteched above file is from openatv 6.2 from 14 April, same crash on PureE2.
Who is bliindscan E2 plugin developer ?
I want this cosmetic to show FEC, for this reason i am feedhunter and FEC is importamt, because i know which feed what FEC use.

I can't tell you, because how i say Symbol rate option missing on openatv 6.3/6.2 and PureE2.

I give video for example to see how have option to choose Symbol rate and option for transponder selection.

What about T2MI ? will have in Zgemma H7/H9 in future ?

**Comment by zgemma-star** [comment]
Silabs doesn't support FEC in HW blindscan only automatic FEC.

T2MI you can use astra-sm
