### ISSUE TITLE
Zgemma H9 Combo NIM Socket

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#43]
hi, please is there any way to fix this? 
want to see so
**NIM Socket 0:
        Type: DVB-S2X
NIM Socket 1:
        Type: DVB-T2**

and now so...

```
root@zgemmah9combo:~# cat /proc/bus/nim_sockets
NIM Socket 0:
        Type: DVB-T2
        Name: Si2168
        Has_Outputs: no
        Frontend_Device: 0
        I2C_Device: 0
        Supports_Blind_Scan: yes
NIM Socket 1:
        Type: DVB-S2X
        Name: Si2166D
        Has_Outputs: no
        Frontend_Device: 1
        I2C_Device: 0
        Supports_Blind_Scan: yes
root@zgemmah9combo:~# 
```

**Comment by zgemma-star** [comment]
You want first the DVB-S2x shown? It depend on the hardware how the tuners are displays.
It's impossible without work-a-rounds to manupilate it. As we avoid if possible all work-a-rounds it will been impossible to adjust it.
I think you want it for configurate in first installation? You can then better hack this that you first setup DVB-S2x tuner.

**Comment by Marchella1983** [comment]
> I think you want it for configurate in first installation? You can then better hack this that you first setup DVB-S2x tuner.

do so 
Tuner A: Si2166D (DVB-S2X) 
Tuner B: Si2168

but not as in the screenshot
![1_0_1_580_14_1_3522E18_0_0_0_20190422062910](https://user-images.githubusercontent.com/28537448/56478337-fef13180-64c7-11e9-9cbc-b19ec790281c.jpg)

**Comment by zgemma-star** [comment]
It's select by hardware which one is tuner A or B. If you want to cosmetic change your only option is to hack Enigma2 so that DVB-S2(x) tuners are shown first.
