### ISSUE TITLE
incorrect putty operation

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#44]
Hello, why Putty displays the log in an incomprehensible form Zgemma H7s
![Снимок экрана в 2019-04-22 17-39-56](https://user-images.githubusercontent.com/28537448/56500899-17903480-6526-11e9-9040-0b9d6c1c201c.png)

for Zgemma H9Combo also does not work properly...
![Снимок экрана в 2019-04-22 17-51-21](https://user-images.githubusercontent.com/28537448/56501224-668a9980-6527-11e9-827c-b6018a5a25af.png)

my Formula F4 turbo works correctly with these settings...
![Снимок экрана в 2019-04-22 17-38-56](https://user-images.githubusercontent.com/28537448/56501264-891cb280-6527-11e9-904e-550d5a98ab07.png)

settings Putty
![Снимок экрана в 2019-04-22 18-10-06](https://user-images.githubusercontent.com/28537448/56506347-9b9ee800-6537-11e9-882b-cd8f075e9305.png)

**Comment by zgemma-star** [comment]
Please ask questions in forum and not in github

**Comment by Marchella1983** [comment]
I do not understand and what's the forum, except for the withdrawal of Putty not the drivers or the boot loader is responsible?

**Comment by Marchella1983** [comment]
Is this not at the driver or bootloader level?

**Comment by atvcaptain** [comment]
its issue with your serial connector, here all file

have nothing todo with driver or kernel
