### ISSUE TITLE
H9S DTS Audio issue

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/meta-zgemma#45]
Dear Zgemma,
On H9S box DTS audio is not working in movies unless downmix DTS to stereo is enabled. Tried openATV 6.2 and 6.3 the same problem exists. AC3 has no issues.
Can you elaborate ?
Regards,

**Comment by zgemma-star** [comment]
Please ask user questions in forums.
When you do passthrough audio it send unmodify audio. Please check your mediacenter /amplifier if it supports DTS.
