### ISSUE TITLE
Zgemma H9 Combo Ci info

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#46]
Hello, I beg you not to scold and do not drive to the forum. In the Zgemma H9 Combo there is one slot Ci and one card reader, I have one Ci + module installed and in CommonInterAssignment it shows the constant initialization of the second module. I was told that this is a driver bug, if this is so please correct this problem.
![1_0_1_580_14_1_3522E18_0_0_0_20190428202505](https://user-images.githubusercontent.com/28537448/56893196-5466a900-6a9b-11e9-9bde-3452d5129cf9.jpg)

**Comment by zgemma-star** [comment]
Seems cosmetic issue in the image. Why would it been a driver bug, please explain with debug log to understand it.

**Comment by Marchella1983** [comment]
in Zgemma H9 Combo, one Ci slot and in CommonInterAssignment it shows two Ci and at what the second is constantly initialized ...

log removed
`enigma2 2> & 1 | tee /tmp/e2.log`

```
_Assignment] activating ci configs:
17:39:25.0933 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2019-04-29 17:39:25+0500 [-] [CI_Activate] activate CI0 with following settings:
17:39:25.0938 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2019-04-29 17:39:25+0500 [-] ([], [], [1617L])
17:39:25.0944 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2019-04-29 17:39:25+0500 [-] [CI_Activate] activate CI1 with following settings:
17:39:25.0949 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2019-04-29 17:39:25+0500 [-] ([], [], [])
```


[e2.log](https://github.com/zgemma-star/meta-zgemma/files/3127390/e2.log)

**Comment by zgemma-star** [comment]
No driver issue but image should control this cosmetic issue.

**Comment by Marchella1983** [comment]
hello please open this issue...
