### ISSUE TITLE
Channels with AC3 Audio Track + Transcoding = No Audio

### ISSUE THREAD

**Issue by ghost** [zgemma-star/meta-zgemma#47]
Hello,

Setup:
Model H9.2H
Current OpenPLI 7.1 with newest drivers.

Problem:
When i transcode channel with ac3 audio track (2.0 or 5.1 does not matter) i got no audio. Mpeg works without problem - but there are channels with ac3 audio only so it would be great to fix ac3 transcode.
Already tried downix on/off - no effect.

Thank you

**Comment by zgemma-star** [comment]
With updates from 15may 2020 a single track audio will as well been transcode to aac
