### ISSUE TITLE
Video sync problems H9

### ISSUE THREAD

**Issue by samuel-obiedzinski** [zgemma-star/meta-zgemma#50]
On some mkv movies which I play from USB stick sound and picture are not synchronized.
I checked different USB sticks and even from USB Hdd there is same problem.
There are no such problem when I use my PC for same mkv playback. 

I also checked these mkv files on H7  owned by my friend and playback was also OK.
So, it looks like the problem is only on H9. 
Could you please help with this problem or maybe I should return my H9 to the seller?

**Comment by samuel-obiedzinski** [comment]
Please could I have some answers?

**Comment by Kerberos1864** [comment]
> Please could I have some answers?

Here there is the same problem

**Comment by Kerberos1864** [comment]
@zgemma-star We all bought the H9s receiver as if there is support for its issues.
I can not find that you are doing any support !

**Comment by zgemma-star** [comment]
Please supply mediacontent

**Comment by samuel-obiedzinski** [comment]
Hi it is not so easy to attach here mkv movie at first because of copyright rights and also because of size, but I am believe that same problem could be produced on any MKV with PCM audio track.

Can you confirm that this working without problems on H9S?

**Comment by zgemma-star** [comment]
MKV with PCM track isn't very common. We need to forward video samples for check if this problem can been solved

**Comment by Kerberos1864** [comment]
> MKV with PCM track isn't very common. We need to forward video samples for check if this problem can been solved

Check this media info of a .mkv file and forward it to service hisilicon please !
**Video**
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 46 min 3 s
Bit rate                    : 8 672 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.174
Stream size                 : 2.79 GiB (85%)
Writing library             : x264 core 142 r2431 ac76440
Encoding settings           : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=8672 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                    : English
Default                     : Yes
Forced                      : No

**Audio**
ID                          : 2
Format                      : DTS
Format/Info                 : Digital Theater Systems
Codec ID                    : A_DTS
Duration                    : 46 min 3 s
Bit rate mode               : Constant
Bit rate                    : 1 509 kb/s
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 93.750 FPS (512 SPF)
Bit depth                   : 24 bits
Compression mode            : Lossy
Stream size                 : 497 MiB (15%)
Language                    : English
Default                     : Yes
Forced                      : No

**Comment by Kerberos1864** [comment]
The H9S receiver is barely playing this movie file and many other 1000 of files like this

**Comment by Kerberos1864** [comment]
@zgemma-star  please Forward this to hisilicon

**Comment by zgemma-star** [comment]
Please supply content media which doesn't work well with Hiplayer and Native player in Kodi.

**Comment by Kerberos1864** [comment]
> Please supply content media which doesn't work well with Hiplayer and Native player in Kodi.

Movie File is about 8GB. I posted above the media info it will help them find the issue

**Comment by Kerberos1864** [comment]
@zgemma-star the problem wasn't from hisilicon it was solved by changing refresh rate to auto which turned zgemma h9s to a monster.
Thanks again for this powerful product !!

**Comment by zgemma-star** [comment]
Thank you for the feedback.
Not all media content can been support by Hisilicon but if something fails please report it.

**Comment by zgemma-star** [comment]
Mkv with PCM track should with latest update been working well.
For new issues open a new thread.

**Comment by samuel-obiedzinski** [comment]
Thank you, so much. How can I test this?
It is possible to install this fix on my current OpenPLI firmware?
