### ISSUE TITLE
to fix InputDeviceSetup

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#54]
on the pure image set in InputDeviceSetup by default RCU Default
![1_0_1F_483_6_1E61_2EE0000_0_0_0_20191103200721](https://user-images.githubusercontent.com/28537448/68087236-a2f36680-fe75-11e9-98e3-981d2871bf8f.jpg)
`root@h9combo:~# cat /proc/stb/ir/rc/type
28
`

I have a Formuler remote and I choose it.
![1_0_1F_483_6_1E61_2EE0000_0_0_0_20191103200958](https://user-images.githubusercontent.com/28537448/68087287-20b77200-fe76-11e9-850b-36c3e2d77771.jpg)
`root@h9combo:~# cat /proc/stb/ir/rc/type
18
`
when I want to switch to my native Zgemma remote is Default, it doesn't work...
you have to choose H.S/H.2S/H.2H/H5/H7
![1_0_1F_483_6_1E61_2EE0000_0_0_0_20191103201432](https://user-images.githubusercontent.com/28537448/68087334-ac310300-fe76-11e9-9a66-1e1540732cfa.jpg)
root@h9combo:~# cat /proc/stb/ir/rc/type
21
the code changes to 21, Default 28 no longer works...

please fix this problem...

**Comment by zgemma-star** [comment]
This should been ask to image makers. It's not driver related

**Comment by atvcaptain** [comment]
we use the settings we get from zgemma

looks zgemma git https://github.com/zgemma-star/meta-zgemma/blob/master/conf/machine/h7.conf#L17

h7 use type 21 and not 28

28 are h9 and h9combo

**Comment by Marchella1983** [comment]
thanks to Captain, now it works...
