### ISSUE TITLE
Netflix for H9 SERIES.

### ISSUE THREAD

**Issue by TheAlbanian** [zgemma-star/meta-zgemma#56]
hello netflix e2 plugin working on Hisilicon Hi3798MV200 future news on H9 Serie ?

**Comment by zgemma-star** [comment]
This is not driver related. 
Netflix needs an uptodate browser and widevine to get it working.

At the moment there is not any good solution. Some manufactures publish quickly a temporary solution which was known to not work for a short periode. If a good stable and reliable solution is available I assume it will come for H9 Series as well

**Comment by TheAlbanian** [comment]
Thank You so much. 
Remember lot of people are waiting dhis Plugin.

**Comment by zgemma-star** [comment]
We released today a patch so that we can use the latest chromium.
The main problem is to get widevine running in the chromium browser and we need somekind of hardware acceleration for the video.

**Comment by TheAlbanian** [comment]
nothing news? long time we are waiting but nothing.
Octagon now have Netflix and Amazon Video
Zgemma no more news.

**Comment by Kerberos1864** [comment]
@TheAlbanian man Zgemma is dead.
I really regret buying this product.
Literally 0% support.

**Comment by TheAlbanian** [comment]
> @TheAlbanian man Zgemma is dead.
> I really regret buying this product.
> Literally 0% support.

Yeah.. so sad. zgemma really no more news.  i'm compare my h9combo with sf8008. octagon on for one year maked on sf8008 netflix, amazon video and soon android. really zgemma nothing news to compare dhis. on dhis way i sure will lost lot of costumers.

**Comment by zgemma-star** [comment]
SF8008, Netflix is pretty bad and similar solutions is given to oe-alliance for the Zgemma products.
It's upto image makers if they use it or not.
The best solution however is Kodi which as well runs on Zgemma.

Second we have a webbrowser which is based on QT5 this is as well not used by image makers.

**Comment by TheAlbanian** [comment]
> SF8008, Netflix is pretty bad and similar solutions is given to oe-alliance for the Zgemma products.
> It's upto image makers if they use it or not.
> The best solution however is Kodi which as well runs on Zgemma.
> 
> Second we have a webbrowser which is based on QT5 this is as well not used by image makers.

i no idea why netflix is bad? dhis is a new now.

**Comment by zgemma-star** [comment]
Use Kodi solution, that's best working solution for now

**Comment by TheAlbanian** [comment]
> Kodi

i'm sorry kodi is not a solution for netflix.
That means no have to waite never Netflix or Amazon Video on H9 Series?

**Comment by zgemma-star** [comment]
Why is kodi not solution, this works at moment far out the best?

The QT solution is easy but you need always to have the latest qtwebengine as it uses the chromebook solutions. So like sf8008 the maintain is huge. This is as well available in oe-alliance https://github.com/oe-alliance/oe-alliance-core/tree/4.4/meta-oe/recipes-qt5.14/qtwebflix

For the emmc flashes an Android image will come in a few months but this will work the best on the H10 model. Which has 2GB DDR but on the 1GB DDR versions it's just ok.
