### ISSUE TITLE
after Restart, there's no picture

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#58]
Hi, it's a problem from the beginning on the Zgemma H9 Combo/Twin, I've been looking for the cause of this problem for a long time and now I've found it, please fix this bug...

I will receive three satellites 56e (Tricolor and NTV+), 75e (MTS tv) and 85e (Telecard), so I noticed that if I turn on my Zgemma H9Combo or Twin from Stanby mode or make a full Restart on the package of channels from satellite 56e, when switching to the package of channels 85e does not show more than one channel but in tmp/ecm.Info shows that the keys are coming, you need to do a full rebutt box to get a picture of the 85e....

**Comment by Marchella1983** [comment]
Happy New Year's Eve!
so I videotaped it so I could understand the problem more clearly...
https://mega.nz/#!hRdXHK4Y!5xLWX5D2clgRQFXShqLy4opsv0YwrGyasbaMNSSYbPg

and so always, if you do a full Zgemma restart on a working provider channel, then the next channel of another provider does not show until the next full Zgemma reboot...

and it's on all the images the Zgemma H9Combo/Twin has on it.

**Comment by arion75** [comment]
I confirm that there is such a problem.

**Comment by Dima73** [comment]
I confirm that there is such a problem.

**Comment by Dima73** [comment]
Yesterday I conducted a survey on the Russian-language forum.
    This is a problem for all users!
    Surprisingly, no one reported this earlier, everyone believed that this was a problem with his module CI(+).

    But this applies to any not FTA channel.

    Two to three hours and you need to reboot the receiver, often only by turning off the power.
