### ISSUE TITLE
Zgemma H9 Twin

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#63]
**zgemma-star** hi, everybody, can you tell me what's in charge of this part of the tuner A/B? 
![1_0_19_553_5_1E61_2EE0000_0_0_0_20200415120557](https://user-images.githubusercontent.com/28537448/79308167-87ef4d00-7f11-11ea-8435-65dfcd3074e1.jpg)

when tuning with the same tuner settings A and B at the same time, tuner B does not work ...

if tuner A is not configured, tuner B works...

please check with you, and if that's not the driver, please fix it...

**Comment by Marchella1983** [comment]
only tuner A works with these settings, tuner B doesn't work...
![1_0_19_553_5_1E61_2EE0000_0_0_0_20200415121901](https://user-images.githubusercontent.com/28537448/79309179-54adbd80-7f13-11ea-9249-31529130d559.jpg)

with these settings only tuner A works, tuner B does not work, or so only tuner A...
![1_0_19_553_5_1E61_2EE0000_0_0_0_20200415122230](https://user-images.githubusercontent.com/28537448/79309563-ee756a80-7f13-11ea-94af-d6e701b55d60.jpg)

Thank you for your understanding and support!

**Comment by zgemma-star** [comment]
There is no internal loopthrough.
How did you connect the coax kabel?

Both tuners are connect to coax? 
What is your advanced settings?

Enigma2 controls which tuner to prefer. It's so normal that tuner A will been first used.
Tuner B only will been activate when Tuner A is "locked/active" like by recording or PiP.

**Comment by Marchella1983** [comment]
in the first screen, the settings are the same for both Tuner A and Tuner B, connecting the cable to Tuner A works and if you connect the cable to Tuner B it doesn't work... 
![screenshot_20200417070424](https://user-images.githubusercontent.com/28537448/79524388-d3246f80-8079-11ea-8481-c0428f2dbfa9.jpg)
![screenshot_20200417070441](https://user-images.githubusercontent.com/28537448/79524394-d91a5080-8079-11ea-8f96-299e98e280f9.jpg)


in the second and third screen, shouldn't the tuner B set as Equal to Tuner A with the cable connected to tuner B work?

**Comment by zgemma-star** [comment]
Two tuners need two signals. 
I think with your explanation you have only one signal. So one coax cable, this is right?

**Comment by Marchella1983** [comment]
Yes, I have one coax cable.

when I had Vu Duo2 and if my memory doesn't change there, tuner A or B worked with one coax cable.

if you think you can properly close the issue...

I'm sorry if I took your time...

**Comment by zgemma-star** [comment]
Probably it had internal loopthrough. 

Satellite signal has 4 bands and with loopthrough only 1 band can been passthrough.
By H9 models this should been done external.
It's always recommand to use unicable or 2 coax kabels.
With use of one and check tuner B you have to disable tuner A.
