### ISSUE TITLE
[h9/10] change linux enable swap

### ISSUE THREAD

**Issue by Dima73** [zgemma-star/meta-zgemma#64]
Please   enable swap
https://github.com/openatv/enigma2/issues/908

https://github.com/oe-alliance/oe-alliance-core/commit/4c56642e1b706a6de52ff06109c5e2c23967cef9

https://github.com/zgemma-star/meta-zgemma/blob/9bad0c65cb06e67e88138e4ea3aa0ad9d7412d6e/recipes-bsp/linux/files/h10/defconfig#L48

https://github.com/zgemma-star/meta-zgemma/blob/9bad0c65cb06e67e88138e4ea3aa0ad9d7412d6e/recipes-bsp/linux/files/h9combo/defconfig#L48

**Comment by zgemma-star** [comment]
In next update this will been activate.

(Box has 1GB ram) we recommend not to use swap.
