### ISSUE TITLE
No audio on PCM/LPCM tracks

### ISSUE THREAD

**Issue by samuel-obiedzinski** [zgemma-star/meta-zgemma#70]
Hi

using last OpenPLI image openpli-7.2-release-h9combo-20200518_emmc.zip the audio is missing on all mkv files with PCM/LPCM tracks.

I think this is related with another issue which was already closed 
https://github.com/zgemma-star/meta-zgemma/issues/50 

please help

**Comment by zgemma-star** [comment]
Openpli 7.2 uses old drivers and do not update it.
You have to wait untill 7.3 is released.
