### ISSUE TITLE
H9S NTFS PROBLEM

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/meta-zgemma#71]
Dears,
NTFS formatted devices cannot be read on the 3.0 USB port of zgemma H9S
Any help ?
I am using latest version 6.3 .
It was working fine on openatv 6.2 (15 may 2019 version).
Regards,

**Comment by Kerberos1864** [comment]
@zgemma-star 
The new H9S box comes with no usb 3.0 port.
But why it should do a problem for me I am using the old model

**Comment by zgemma-star** [comment]
NTFS-3G maybe not installed?

I think you should first check the image and see if you can mount the disk. When it fails then a log is helpful.
The issue is probably image related as NTFS is done by linux kernel and mount by the image. It's not really driver related.

**Comment by Kerberos1864** [comment]
@zgemma-star all drivers installed, ntfs-3g updated too. Since ntfs is working fine on 2.0 port
Will check with openatv but I dont think its image related since all new version of images are not reading ntfs devices on the 3.0 port

**Comment by Kerberos1864** [comment]
Old versions which were released before the new H9S modelwork normaly with ntfs on that port.

**Comment by Kerberos1864** [comment]
@zgemma-star debug log is on now.
When I plug the ntfs disk to that port nothing happened at all nothing !!

**Comment by zgemma-star** [comment]
How did you activatie extra debug?
lsusb, dmesg, mount, df are standard available

**Comment by Kerberos1864** [comment]
Using mount command
When NTFS plugged in usb 2.0 port:

dev/sda1 on /media/hdd type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)

When this device is plugged in 3.0 port:
Nothing...

**Comment by zgemma-star** [comment]
Nothing means your stick or the box USB is damaged and I cannot help you further.

Please provide correct information and log. I told you in previous message already what you minimal should have report.

**Comment by Kerberos1864** [comment]
@zgemma-star please listen carefully I will explain further.
I tried like 10 types of external harddisks which are working fine on the usb 2.0 port, but not being read on the 3.0 port. All of them are NTFS formatted.
This means that they are not damaged and ntfs libraries and drivers are installed correctly since
they are being functioning normally on the USB 2.0 port.
I hope now everything is clear.
You can test on zgemma H9S box without built in wifi module and check the problem.

**Comment by Kerberos1864** [comment]
What type of evidence you need ? I can provide you with all.
Thank you

**Comment by zgemma-star** [comment]
Things like lsusb, dmesg, mount, df 
You load xhci, ehci and ohci?

**Comment by Kerberos1864** [comment]
@zgemma-star ,
The following harddisk inserted in USB 2.0 port we get the following output of dmesg:

![2 0](https://user-images.githubusercontent.com/45090310/82916068-38715780-9f7a-11ea-930a-666105e729f3.png)

The same  harddisk inserted in USB 3.0 port we get the following output of dmesg:
Full message
[new.txt](https://github.com/zgemma-star/meta-zgemma/files/4683531/new.txt)






This log of dmesg is  before pluging any external harddisks
[dmesg.txt](https://github.com/zgemma-star/meta-zgemma/files/4683055/dmesg.txt)

**Comment by zgemma-star** [comment]
new.txt

scsi 0:0:0:0: Direct-Access     ST500LT0 12-9WS142        0001 PQ: 0 ANSI: 6
random: nonblocking pool is initialized
sd 0:0:0:0: [sda] 976773168 512-byte logical blocks: (500 GB/466 GiB)
sd 0:0:0:0: [sda] 4096-byte physical blocks
sd 0:0:0:0: [sda] Write Protect is off
sd 0:0:0:0: [sda] Mode Sense: 2f 00 00 00
sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
 sda: sda1
sd 0:0:0:0: [sda] Attached SCSI disk

Device /dev/sda1 is available. So everything is working fine!!!

It seems you do not mount the disk to a map but that's depend on your settings and image.
try follow:
mkdir -p /tmp/ntfs-test
mount /dev/sda /tmp/ntfs-test

Log last lines of dmesg and df

**Comment by Kerberos1864** [comment]
Sorry the file was on the 2.0 port
This is the new file
[new.txt](https://github.com/zgemma-star/meta-zgemma/files/4683529/new.txt)
 I edited the above comment with right file

**Comment by zgemma-star** [comment]
NTFS with USB sticks works fine on USB3.0

Your disk seems not to spin up. Try external powersupply (which is always recommand by USB hdd)
