### ISSUE TITLE
H9S NTFS PROBLEM ( Don't close)

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/meta-zgemma#74]
Dear @zgemma-star 
You can't close the issue and its not solved yet.
You said something about power ? I told you that 10 drives have been tested and even flash usb drives (NTFS)  which doesn't require power are not read on the USB 3.0 port unless I format them to FAT32.
You can't even test by yourself on the Zgemma H9S ?
![20200526_195347](https://user-images.githubusercontent.com/45090310/82928347-cb19f280-9f8a-11ea-95b8-a91b52370b97.jpg)

If you want to assume that USB 3.0 port is damaged, its working fine on openATV 6.2 (15-05-2019)
You should really test by yourself before judging I am using openATV 6.3 today version.

**Comment by Kerberos1864** [comment]
I really want to close the issue but you are the only one who can help regarding this problem.
I tried everything .....

**Comment by zgemma-star** [comment]
Kingston USB stick on left I have test with same stick.
Difference is defconfig your using. We never prefer UAS.

You format it in windows 10 as NTFS ?
So when you place the stick into the box.
Then dmesg you must see something. When not I advice to install an Openpli image. They use no UAS.

**Comment by Kerberos1864** [comment]
I formatted the USB stick to ntfs again using Windows 10 but same problem.
Nothing in  dmesg check the file.
[DMESG.txt](https://github.com/zgemma-star/meta-zgemma/files/4684027/DMESG.txt)

What version of openpli you recommend for testing so the issue in openATV you assume ?

**Comment by zgemma-star** [comment]
Openpli 7.2 is latest, by me USB with NTFS works fine on USB3.0 port

**Comment by Kerberos1864** [comment]
Will test in few moments

**Comment by Kerberos1864** [comment]
Ok now we have a new conclusion after testing latest version of openpli 7.2:
Flash USB stick formatted to NTFS and plugged into the USB 3.0 port it worked successfully.
BUT formatted two external harddisks to NTFS again both did work on USB 2.0 port and didn't on 3.0 port(TESTED with power cables too )
I think the problem is with external hdds formatted with NTFS @zgemma-star

**Comment by zgemma-star** [comment]
This problems are all kernel related. You can try forums to solve your problem.
Probably everyone would advice to use the standard ext3/4

**Comment by Kerberos1864** [comment]
You are not responsible for kernel issues ?
Ext3/4 supported by windows ?

**Comment by zgemma-star** [comment]
NTFS is a windows system and not Linux. 
Kernel parts like NTFS are support and maintain by the kernel.

The ext3/ext4 partitions can been easily access by ftp in windows.

**Comment by Kerberos1864** [comment]
Its not a good solution, @zgemma-star who is responsible for the kernel part in zgemma ?
This should be fixed ASAP, usb 3.0 is important when watching high size files 4K movies without slowness of reading from disk.
We can't stay in very old versions of firmware just inorder to benefit from usb 3.0 port which can read ntfs.

**Comment by zgemma-star** [comment]
NTFS is the file system of Microsoft Windows NT, 2000, XP and 2003.

The only right solution is to use EXT3/EXT4.

**Comment by Kerberos1864** [comment]
The only solution ?
Majority of people use Windows for your notice, and NTFS is not old nor useless as you
assume its still being used by now 90% of people.
I use all my external harddisk on windows workstations and even at work.
You want me to format to EXT4 just because "sorry" you can't do some work ?
@zgemma-star you really should find another solution.

**Comment by zgemma-star** [comment]
Oe-alliance/Captain found maybe a working solution by install tntfs.

Please remember that the box is LinuxOS and not Microsoft Windows

**Comment by Kerberos1864** [comment]
TNTFS ? How can I test that ?
@atvcaptain @zgemma-star can you please elaborate ?

**Comment by atvcaptain** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/7caa1cfc2ef10ea115c2cdb6ebc547e4631f5c7c

**Comment by Kerberos1864** [comment]
Thanks @atvcaptain ,
When can we test ? Tomorrow ?

**Comment by atvcaptain** [comment]
1-3 days you see when new image online

**Comment by Marchella1983** [comment]
> 1-3 days you see when new image online

Captain hi, please add these ATV edits too.
https://github.com/OpenPLi/openpli-oe-core/commit/8be809a5ed9444e99c8fabf62888bbc9c4854f99#diff-f306574ccbe278273b9d11e2b382a1a3
https://github.com/OpenPLi/enigma2/commit/650469727a1c2a62177bcd0ce1658f6f9ced31b3

**Comment by Kerberos1864** [comment]
Dears @zgemma-star and @atvcaptain ,
Installed the image today **openatv-6.3-zgemmah9s-20200530_usb**
The NTFS disks still not working on the USB 3.0 port.
Check dmesg log

tntfs: module license 'Commercial. For support email ntfs-support@tuxera.com.' taints kernel.
Disabling lock debugging due to kernel taint Tuxera NTFS driver 3017.7.4.6 [Flags: R/W MODULE].
Built against headers 4.4.35_hi3798mv2x 
#1 SMP Tue Dec 12 14:16:24 CST 2017 arm Running on kernel 4.4.35
 #1 SMP Thu May 28 17:20:10 UTC 2020 armv7l
**WARNING: Running kernel does not match configured kernel headers the driver was built with!  The driver needs to be rebuilt with the correct kernel headers!**

[dmesgLog.txt](https://github.com/zgemma-star/meta-zgemma/files/4706170/dmesgLog.txt)

**Comment by Kerberos1864** [comment]
Any news @atvcaptain @zgemma-star ?

**Comment by Kerberos1864** [comment]
@zgemma-star closing the issue again and the problem is not solved yet ?

**Comment by zgemma-star** [comment]
https://github.com/openatv/enigma2/issues/1680

One issues report about your point is enough. Don't start multiply topics.
NTFS system is a Windows filesystem as from start we advice to use EXT3/EXT4.
No other good solution is till now available
