### ISSUE TITLE
H10 combo incorrect output of /proc/stb/info/boxtype

### ISSUE THREAD

**Issue by Marchella1983** [zgemma-star/meta-zgemma#99]
Of course, I don't believe in miracles anymore, but I will still try to ask to correct this discrepancy...

If you can please correct this irrelevant command
https://forums.openpli.org/topic/85002-zgemma-h10-combo/?view=findpost&p=1372618

![4097_0_1_2707_1356_EE91_1010101_0_0_1_20210812170204](https://user-images.githubusercontent.com/28537448/129215475-f7c327f1-4f0f-428e-b962-237a34e5f017.jpg)

**Comment by zgemma-star** [comment]
H10 never went in production. You have "free" test hardware for only test and not commercial use.
If you want to use it for own commercial use, probably best is to install fastboot from h10 and image and bootargs from h9combo.

**Comment by Marchella1983** [comment]
It didn't go into production and yet you still manage to sell it... I bought it on Ali with my own money... What makes you think I got it for free?

As I wrote above, I no longer believe in miracles... We users have long ago lost hope in you that you will fix what should work already at the start of sales...
